services:
  - type: web
    name: vyorius-drones-backend
    runtime: node
    plan: free
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://vyorius-drones.vercel.app
